#!/usr/bin/env python3
"""
delete_supabase_junk.py — Xóa 788 items rác khỏi Supabase theo danh sách đã review.

Chạy sau khi user confirm YES.
"""

import os
import sys
from pathlib import Path

# Load .env
repo_root = Path(__file__).resolve().parents[4]
env_path = repo_root / ".env"
if env_path.is_file():
    with open(env_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                os.environ[k] = v

SUPABASE_URL = os.getenv("SUPABASE_URL")
SERVICE_ROLE_KEY = os.getenv("SERVICE_ROLE_KEY")  # Use service role key for admin operations

if not SUPABASE_URL or not SERVICE_ROLE_KEY:
    print("❌ Thiếu SUPABASE_URL hoặc SERVICE_ROLE_KEY trong .env")
    sys.exit(1)

# Danh sách 788 items cần xóa (từ check_master_sync output)
JUNK_ITEMS = {
    "fields": [
        "E2E_SCI", "CNTT", "DCM", "MPC", "NET", "BRA", "GEN", "TEST_TECH", "TEST_ART",
        "TEST_BUS", "DES", "TEST_WRITE", "KHCB", "TEST_SCI"
    ],
    "subjects": [
        "TEST_CHEM", "TEST_PROG", "TEST_NET", "TEST_DESIGN", "TEST_MUSIC", "TEST_MGMT", "TEST_FIN",
        "IT", "TKDH", "MATH", "C_PROGRAMMING", "ELECTRONICS_CIRCUITS", "EMBEDDED_SYSTEMS",
        "SENSOR_ACTUATOR_TECH", "WIRELESS_CONN", "IOT_PROTOCOLS", "CLOUD_COMPUTING",
        "INFO_SECURITY", "DATA_ENGINEERING", "DATA_SCIENCE", "DATA_VISUALIZATION",
        "IOT_APP_DEV", "SMART_INTERFACES", "BACKEND_DEV", "SYSTEM_ARCHITECTURE",
        "PROFESSIONAL_PRACTICE", "TEST_PHY", "E2E_PHY"
    ],
    "categories": [
        "TEST_MECH", "LQVT", "PARADIGMS_MODELS", "TEST_INV", "TEST_ALGO", "DF", "C_SYNTAX_BASICS",
        "PMTK", "DECLARATIVE_UI_MODEL", "KTVT", "KTCSA", "C_CONTROL_LOGIC", "C_MODULARITY",
        "CIRCUIT_BASICS", "ARDUINO_PLATFORM", "SPPT", "GPIO_CONTROL", "SENSOR_INTEGRATION",
        "DISPLAY_TECH", "LOCAL_WIRELESS", "WIFI_NETWORKING", "EMBEDDED_WEB_TECH",
        "DEVELOPMENT_ENVIRONMENT", "LPWAN_TECH", "MESSAGING_PROTOCOLS", "P2P_COMM",
        "CLOUD_IOT_PLATFORMS", "SERVERLESS_COMPUTE", "IOT_THREATS", "SECURE_OPS",
        "DATA_STORAGE_LOCAL", "NOSQL_DATABASES", "DATA_PROCESSING", "DATA_VIZ_TOOLS",
        "UI_UX_PRINCIPLES", "NO_CODE_APPS", "DASHBOARD_ENG", "VOICE_INTERFACES",
        "API_DEVELOPMENT", "IOT_ARCH_PATTERNS", "CAPSTONE_PROCESS", "IOT_SOCIETY",
        "GRAPHIC_DESIGN_PRINCIPLES", "DIGITAL_INTERACTION", "COLLABORATION_TOOLS",
        "E2E_MECH", "TEST_PERF", "TEST_STRAT", "TEST_OPS", "TEST_ACCT", "TEST_VIS",
        "TEST_TYPO", "TEST_THEORY", "TEST_LANG", "TEST_PROTO", "TEST_HW"
    ],
    "topics": [
        "SOFTWARE_PROTOTYPING", "PROCESS_VALIDATION", "ACCESSIBILITY_DESIGN_AND_EVALUATION_METHODS",
        "C_ENV_SETUP", "VAR_DATATYPES", "IO_FORMATTING", "RELATIONAL_LOGIC_OPS", "CONDITIONAL_STMTS",
        "LOOPING_CONSTRUCTS", "XCODE_BASICS", "PROGRAMMING_PARADIGMS", "SWIFT_SYNTAX", "FUNCTIONS_PARAMS",
        "MCU_PLATFORMS", "ARRAYS_HANDLING", "ELECTRONIC_COMPONENTS", "SOFTWARE_POST_DEVELOPMENT_ISSUES",
        "TCPT", "OBJECTS", "SOCIOECONOMIC_IMPACT", "TEXT", "DESIGN_AIDS", "ARDUINO_IDE_SKETCH",
        "DIGITAL_IO_CONTROL", "ANALOG_PWM_CONTROL", "AI_ML", "PHCCB", "ENV_SENSORS", "SHAPE_TOOLS",
        "TEXT_TOOLS", "FILE_FORMATS", "MOTION_SENSORS", "LED_DISPLAYS", "I2C_DISPLAYS", "BLUETOOTH_HC05",
        "WIFI_CONN_MODES", "IDE_TOOLS", "SWIFT_SYNTAX_RULES", "PANELS", "DUONG_HINH_KHOI", "DOI_TUONG_VECTOR",
        "VE_CO_PATH", "ARTBOARDS", "HIEU_UNG_LOP", "CONG_CU_VECTOR", "KICH_THUOC_CAT_GHEP", "BO_LOC",
        "STUDIO_DEVELOP", "COMPUTING_IMPACT", "EMBEDDED_SERVER", "WEB_AJAX_UI", "LORA_P2P", "LORAWAN_ARCH",
        "PHOTOSHOP", "ILLUSTRATOR", "LAYERS", "MQTT_ESSENTIALS", "ADJUSTMENTS", "COLOR", "IDE_MANAGEMENT",
        "JSON_PACKAGING", "COAP_BASICS", "SWIFT_SYNTAX_BASICS", "ESP_NOW_PROTOCOL", "CLOUD_IOT_CORE",
        "A11Y_STANDARDS", "SERVERLESS_FUNCS", "AFFINITY", "STUDIO_LIQUIFY", "IOT_THREAT_ANALYSIS",
        "STUDIO_TONE_MAPPING", "VUNG_CHON_PIXEL", "VE_RASTER", "CHINH_SUA_ANH", "SOCIAL_LEGAL_IMPACT",
        "KENH_MAU", "SECURE_MQTTS", "SECURE_OTA", "UI_PROGRAMMING_PARADIGMS", "SD_CARD_LOGGING",
        "GOOGLE_SHEETS_LOG", "MACRO_HANG_LOAT", "XU_LY_ANH", "CHINH_SUA_ANH_NC", "CONG_CU_CHINH_SUA_ANH",
        "NOSQL_STORE", "PANDAS_PROCESSING", "IDE_NAVIGATION", "PYTHON_CHARTS", "UX_DESIGN_PRINCIPLES",
        "BLYNK_IOT_APP", "MIT_APP_INV_PROJ", "DEBUGGING_TECHNIQUES", "NODE_RED_DASH", "COLOR_THEORY",
        "TYPOGRAPHY", "VOICE_IFTTT", "RESOLUTION", "IMAGE_SIZE", "REST_API_PYTHON", "PIXEL_SELECTION",
        "SELECTION_TOOLS", "IOT_SYS_DESIGN", "RETOUCHING", "CAPSTONE_MGMT", "CLONING_HEALING",
        "IOT_ETHICS_TRENDS", "RASTER_PAINTING", "PAINTING_TOOLS", "OPTIMIZATION", "PREPARING_FOR_OUTPUT",
        "PROJECT_MANAGEMENT", "COPYRIGHT", "CLIENT_BRIEF", "REQUIREMENTS_ANALYSIS", "ASSET_MANAGEMENT",
        "COMMUNICATION", "DESIGN_PRINCIPLES", "COMPOSITION", "DIGITAL_IMAGING_TERMS", "DF_PRINCIPLES",
        "DF_PROJECT_MGMT", "KTCSA_SPECS", "KTCSA_SELECTION", "KTCSA_RETOUCH", "E2E_KINEM", "KTVT_OBJECTS",
        "ARCHIVING", "TEST_T_AGILE", "TEST_T_BOND", "TEST_T_COLOR", "TEST_T_EQUITY", "TEST_T_GRAPH",
        "TEST_T_GRID", "TEST_T_HARMONY", "TEST_T_HTTP", "TEST_T_INSTR", "TEST_T_LAYOUT", "TEST_T_LEAN",
        "TEST_T_LEDGER", "TEST_T_OKR", "TEST_T_ROUTER", "TEST_T_SCALES", "TEST_T_SERIF", "TEST_T_SORTING",
        "TEST_T_STAGE", "TEST_T_SWITCH", "TEST_T_SWOT", "TEST_T_SYNTAX", "TEST_T_TAX", "TEST_T_TCP",
        "TEST_T_TYPES", "JAVASCRIPT_DOM", "ABSTRACTION_LAYERS", "PROBLEM_DECOMPOSITION",
        "CREATIONAL_PATTERNS", "STRUCTURAL_PATTERNS", "TYPES_OF_AI", "IOT_SECURITY_THREATS",
        "IOT_SAFETY_RISKS", "AGILE_PRINCIPLES", "SCRUM_ROLES_EVENTS", "RELATIONAL_VS_NONRELATIONAL",
        "ALGORITHMIC_BIAS_SOCIETY", "AI_BIAS", "USER_CENTERED_DESIGN", "AFFORDANCES_SIGNIFIERS",
        "DATA_ENCODING", "CHART_TYPES", "CLOUD_MODELS_IAAS_PAAS_SAAS", "CLOUD_DEPLOYMENT_MODELS",
        "VIRTUALIZATION", "BEHAVIORAL_PATTERNS", "VERSION_CONTROL_WORKFLOW", "AI_HISTORY_MILESTONES",
        "FRONTEND_FRAMEWORKS", "BACKEND_FRAMEWORKS", "FEEDBACK_AND_RESPONSE", "INFORMATION_CREDIBILITY",
        "DIGITAL_FOOTPRINT", "CYBERBULLYING", "COPYRIGHT_CREATIVE_COMMONS", "DIGITAL_DIVIDE",
        "IMAGE_WARPING", "IMAGE_RETOUCHING", "IMAGE_COMPOSITING", "TWO_FACTOR_AUTH", "MAPREDUCE_CONCEPT",
        "CAP_THEOREM", "NEURAL_NETWORKS_BASICS", "AI_VS_ML", "USABILITY_TESTING", "STATISTICAL_MEASURES",
        "PROBABILITY_BASICS", "APP_EXTENSION_MODEL", "DATA_DISTRIBUTIONS", "DATA_COLLECTION",
        "MAP_ANNOTATIONS", "WIDGETKIT_INTEGRATION", "VIEW_LIFECYCLE", "DIGITAL_CITIZENSHIP",
        "UI_ARCH_PATTERNS", "DEVELOPMENT_PROCESS"
    ],
    "concepts": [
        "XCODE_LAYOUT_NAV", "XCODE_ASSETS_CATALOG", "SWIFT_IDENTIFIER_NAMING", "SWIFT_TYPE_SYSTEMS",
        "PARADIGM_THEORY", "VE_NET_CO_PATH", "LKMT", "PHCCB", "SUA_NET_CO_PATH", "THEM_XOA_ARTBOARDS",
        "A11Y_UI_EVALUATION", "SOCIOECONOMIC_IMPACT_ANALYSIS", "MATH", "C_MAIN_ENTRY", "C_COMMENTS",
        "ABOUT_LAYERS", "CREATING_LAYERS", "RENAMING_LAYERS", "LAYER_OPACITY", "STATE_PROPERTY_WRAPPER",
        "PROJECT_ASSETS_MANAGEMENT", "SYNTAX_VS_RUNTIME_ERRORS", "TCPT_PROPERTIES", "PRINTF_FORMAT",
        "DECLARATIVE_UI_PARADIGM", "SCANF_ADDRESS", "FILL_LAYERS", "ESCAPE_SEQS", "C_APP_DESIGN_CYCLE",
        "NETWORK_TOPOLOGIES", "C_DECLARATIVE_UI", "C_LOOP_STRUCTURES", "C_IDE_NAVIGATION",
        "C_UI_LAYOUT_CONTAINERS", "C_DATA_SECURITY_PRIVACY", "C_ASSET_MANAGEMENT", "MODULUS_OP",
        "INVERSE_RELATIONSHIP", "INC_DEC_OPS", "COMPARISON_OPS", "APPLYING_ADJUSTMENTS", "COLOR_ADJUSTMENTS",
        "FRONTEND_FRAMEWORKS", "C_UI_ACCESSIBILITY", "BACKEND_FRAMEWORKS", "C_CONDITIONAL_STATEMENTS",
        "C_STATE_MANAGEMENT", "CURVES_ADJUSTMENT", "LEVELS_ADJUSTMENT", "ABOUT_COLOR", "COLOR_MODELS",
        "C_DEBUGGING_TECHNIQUES", "C_VARIABLE_DECLARATION", "C_TYPE_INFERENCE", "COLOR_SPACES",
        "GRADIENT_FILLS", "SELECTING_COLORS", "ALIGNING_OBJECTS", "GROUPING_OBJECTS", "TRANSFORMING_OBJECTS",
        "ARTISTIC_TEXT", "FRAME_TEXT", "UI_MODIFIERS_CONCEPT", "SNAPPING", "RULERS", "GENERATE_IMAGE_AI",
        "REMOVE_BACKGROUND_AI", "SELECT_SUBJECT_AI", "ELLIPSE_TOOL", "RECTANGLE_TOOL", "POLYGON_TOOL",
        "ARTISTIC_TEXT_TOOL", "LOGICAL_OPS", "IF_ELSE_STRUCT", "SUPPORTED_RAW_FILES", "LAYERS_PANEL",
        "COLOR_PANEL", "ADJUSTMENT_PANEL", "HISTORY_PANEL", "TRANSFORM_PANEL", "ABOUT_DUONG_HINH_KHOI",
        "VE_DUONG_HINH_KHOI", "DEBUGGING", "RETURN_VALUES_AND_SCOPE", "DATA_TYPES", "CONTROL_FLOW",
        "VISUAL_DESIGN", "SECURITY_CHALLENGES", "OPERATORS", "NHAY_CAM_AP_LUC", "SUA_AP_LUC_TREN_TRANG",
        "ABOUT_HINH_HOC", "VE_SUA_HINH_HOC", "MA_QR", "DAU_MUI_TEN", "KIEU_NET_CHAM_GACH", "KIEU_NET_VAN_HOA",
        "STRUCTURE_TYPE", "ARRAYS", "DESIGN_CYCLE", "SENSITIVE_DATA", "ACCESSIBILITY", "FUNCTIONS_AND_PROCEDURES",
        "IOT_PROTOCOLS_MQTT", "CHON_CAN_CHINH_NODE", "BIEN_DOI_DUONG_CONG_HINH", "MO_RONG_STROKE",
        "UI_CONTROLS", "SHAPE", "LOOP_STRUCTURES", "VARIABLES_AND_CONSTANTS", "NAMING_CONVENTIONS",
        "CONTAINER_VIEWS", "VIEW_HIERARCHY", "LEGAL_ETHICAL_SOCIOECONOMIC_IMPACTS", "COLOR",
        "CONDITIONAL_STATEMENTS", "IMPERATIVE_PROGRAMMING", "VIEW_CONCEPT", "TYPE_SYSTEM", "BO_GOC_HINH_KHOI",
        "CHE_DO_TO_MAU", "CAT_DOI_TUONG", "TO_MAU_VUNG", "TOAN_TU_BOOLEAN", "FUNC_DEFINITION", "SYMBOLS",
        "BIEN_DOI_QUANH_DIEM", "IMAGE_TRACE", "BIEN_DANG_WARP", "PASS_BY_VALUE", "RETURN_STATEMENT",
        "CAN_CHINH_PHAN_BO_ARTBOARDS", "DI_CHUYEN_NOI_DUNG_ARTBOARD", "XUAT_ARTBOARDS",
        "APPLYING_LAYER_FX", "FX_3D", "FX_BEVEL_EMBOSS", "FX_COLOR_OVERLAY", "FX_GAUSSIAN_BLUR",
        "TERNARY_OP", "DO_WHILE_LOOP", "ARRAY_DECLARATION", "FX_INNER_SHADOW", "FX_OUTER_GLOW",
        "FX_OUTER_SHADOW", "FX_OUTLINE", "AREA_TOOL", "ARTBOARD_TOOL", "COLOR_PICKER_TOOL",
        "CONTOUR_TOOL", "POINT_TRANSFORM_TOOL", "SHAPE_BUILDER_TOOL", "FETCH_API", "LORA_LIB_USAGE",
        "LORAWAN_ARCH", "BUTTON_BOUNCE", "ARDUINO_SKETCH", "SERIAL_BAUD", "BASIC_MECHANISMS",
        "TRANSPARENCY_TOOL", "PATH_BRUSH_TOOL", "VECTOR_CROP_TOOL", "VECTOR_FLOOD_FILL_TOOL",
        "VIEW_TOOL", "ZOOM_TOOL", "DOI_KICH_THUOC_ANH", "DOI_KICH_THUOC_CANVAS", "PINMODE_FUNC",
        "DIGITAL_RW", "E2E_VEL", "BASIC_ELECTRONIC_COMPONENTS", "CIRCUIT_PRINCIPLES", "CAT_XEN_DOI_TUONG",
        "BIEN_DANG_LUOI", "PHOI_CANH", "XOAY_LAT_CANVAS", "CHIEU_PHOI_CANH", "CHIEU_HINH_CAU",
        "AP_DUNG_BO_LOC", "BO_LOC_THIEN_VAN", "BO_LOC_LAM_MO", "BO_LOC_BIEN_DANG",
        "BO_LOC_NHAN_DIEN_CANH", "BO_LOC_NHIEU_HAT", "BO_LOC_LAM_NET", "AP_DUNG_ANH", "KHOI_SUONG_MU",
        "SU_DUNG_PLUGIN", "TAO_VUNG_CHON_PIXEL", "VE_VUNG_CHON_PIXEL", "VE_HINH_VUNG_CHON_PIXEL",
        "VUNG_CHON_THEO_DAI_MAU", "TINH_CHINH_CANH_VUNG_CHON", "LUU_TAI_VUNG_CHON", "VE_NET_CO_RASTER",
        "DOI_XUNG_GUONG", "TAO_CO_RASTER_TUY_CHINH", "RETTOUCHING", "KHU_MAT_DO", "XOA_TI_VET",
        "NHAN_BAN_CHUA_LANH", "INPAINTING", "VA_ANH", "TACH_TAN_SO", "GHEP_ANH_PANORAMA", "GHEP_ANH_PHOI_SANG",
        "XOA_VAT_THE_STACKS", "GHEP_ANH_LAY_NET", "GHEP_ANH_THIEN_VAN", "CROP_TOOL", "HEALING_BRUSH_TOOL",
        "CLONE_BRUSH_TOOL", "TEST_C_VAR_DECL", "TEST_C_LOOPS", "AFF_DOC_MANAGEMENT", "AFF_FILE_IMPORT",
        "SELECTION_BRUSH_TOOL", "PAINT_BRUSH_TOOL", "ERASE_BRUSH_TOOL", "PULLUP_INTERNAL", "L298N_CONTROL",
        "DHT_LIBRARY", "AFF_OVERVIEW", "AFF_UI_CUSTOMIZATION", "AFF_UI_LAYOUT", "LAYER_CLIPPING",
        "TONAL_ADJUSTMENTS", "PARAGRAPH_FORMATTING", "CHARACTER_FORMATTING", "GRIDS_GUIDES",
        "FRAME_TEXT_TOOL", "SUPPORTED_FILE_FORMATS", "SUA_DUONG_HINH_KHOI", "VE_NET_BUT_CHI",
        "DA_STROKE_FILL", "TAO_VIEN_DONG_DANG", "TAO_HINH_KHOI_COMPOUND", "CUSTOM_PATH_BRUSHES",
        "ABOUT_ARTBOARDS", "FX_GRADIENT_OVERLAY", "FX_INNER_GLOW", "KNIFE_TOOL", "CORNER_TOOL",
        "FILL_TOOL", "STROKE_WIDTH_TOOL", "STYLE_PICKER_TOOL", "DOI_KICH_THUOC_PIXEL_ART",
        "CAT_XEN_ANH", "BO_LOC_MAU_SAC", "TO_MAU_VUNG_CHON_PIXEL", "XOA_ANH", "PHA_TRON_MAU",
        "THAY_THE_MAU_BANG_CO", "CHONG_ANH_STACKS", "INPAINTING_BRUSH_TOOL", "DODGE_BRUSH_TOOL",
        "BURN_BRUSH_TOOL", "BREADBOARD_RAILS", "RESISTOR_COLOR", "LED_POLARITY", "PASSWORD_STRENGTH",
        "ADC_CONCEPT", "PWM_DUTY", "MAP_FUNC", "TROUBLESHOOTING_METHODOLOGY", "ARDUINO_BASICS",
        "LONGPRESS_GESTURE", "7SEG_MULTIPLEX", "I2C_ADDRESS", "LCD_LIB", "STATIC_MEMBERS",
        "IMMUTABILITY", "EVENT_HANDLERS", "STRUCTURED_ONDEVICE_DB", "UI_ANIMATION", "TRANSPORT_PROTOCOLS",
        "FIRST_CLASS_FUNCTIONS", "ERROR_MESSAGES", "RASPBERRY_PI_BASICS", "NETWORK_PROTOCOLS",
        "INHERITANCE_POLY", "ROUTERS_SWITCHES", "PHYSICAL_MEDIA", "ASYNCHRONOUS_PROG", "MALWARE_TYPES",
        "IP_DHCP_GATEWAY", "WIFI"
    ]
}

def delete_batch(table, codes):
    """Xóa batch records từ Supabase table."""
    import requests
    url = f"{SUPABASE_URL}/rest/v1/{table}"
    headers = {
        "apikey": SERVICE_ROLE_KEY,
        "Authorization": f"Bearer {SERVICE_ROLE_KEY}",
        "Content-Type": "application/json",
        "Prefer": "return=minimal"
    }
    # Supabase REST API: DELETE với IN filter
    # Format: code=in.(code1,code2,...)
    if not codes:
        return 0
    # Chunk size 100 để tránh URL quá dài
    deleted = 0
    for i in range(0, len(codes), 100):
        chunk = codes[i:i+100]
        params = {"code": f"in.({','.join(chunk)})"}
        try:
            resp = requests.delete(url, headers=headers, params=params, timeout=30)
            if resp.status_code in (200, 204):
                deleted += len(chunk)
                print(f"  ✅ Deleted {len(chunk)} from {table}")
            else:
                print(f"  ⚠️ {table} chunk failed: {resp.status_code} - {resp.text[:200]}")
        except Exception as e:
            print(f"  ❌ {table} chunk error: {e}")
    return deleted

def main():
    print("🗑️  BẮT ĐẦU XÓA 788 ITEMS RÁC KHỎI SUPABASE")
    print("=" * 60)
    
    total_deleted = 0
    for table, codes in JUNK_ITEMS.items():
        print(f"\n📋 {table.upper()}: {len(codes)} items")
        deleted = delete_batch(table, codes)
        total_deleted += deleted
        print(f"   → Đã xóa: {deleted}/{len(codes)}")
    
    print(f"\n{'='*60}")
    print(f"🎯 TỔNG CỘNG: {total_deleted} items đã xóa khỏi Supabase")
    print("✅ Hoàn tất dọn dẹp Supabase")

if __name__ == "__main__":
    main()